# This is a basic workflows to help you get started with actions

name: CI 

# Controls when the workflow will run 
on: 
  # Triggers with workflow on push or pull request events but only for the main branch
  push: 
    branches: [ main ]
  pull_requests:
    branches: [ main ]
  
  #Allows you to run this workflow manually from actions tab
  workflow_dispatch:
  
  # A workflow run is made of one or more jobs that can be run sequantially or in parallel
  jobs:
  
  # A workflow contains a single job called 
  build:
  
  # 
    runs-on: ubuntu-lates
    
    steps: 
      - uses: actions/checkout@v3
      
      - name: Run a one-line script
      - run: echo Hello, world
      
      - name: Run multi-line scripts
      - run: |
        echo Add action 
        echo test, and deploy 
        
      
    
